import type { Metadata } from 'next'

import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Stream',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="">
      <Header />
      {children}
    </div>
  )
}
