import type { Metadata } from 'next'
import { Inter, Lato, Poppins } from 'next/font/google'

import { QueryProvider } from '@/providers/useQueryProvider'
import NextAuthSessionProvider from '@/providers/sessionProvider'

import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import AdSense from '@/components/ad-sense'

const lato = Inter({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Stream',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={lato.className} lang="pt">
      <head>
        <AdSense pId="ca-pub-4707731953261449" />
      </head>
      <body className={`bg-slate-950 text-zinc-50 antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthSessionProvider>
            <QueryProvider>{children}</QueryProvider>
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
