import type { Metadata } from 'next'

import { Poppins } from 'next/font/google'
import { QueryProvider } from './providers/useQueryProvider'

import './globals.css'
import Header from '@/components/header'

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Stream',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`bg-zinc-950 text-slate-100 ${poppins.className}`}>
        <QueryProvider>
          <Header />
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}
